// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"time"
)

// Defines values for HealthStatusStatus.
const (
	Degraded HealthStatusStatus = "degraded"
	Ok       HealthStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatusStatus enum.
func (e HealthStatusStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for ItemVerdictStatus.
const (
	AVAILABLE      ItemVerdictStatus = "AVAILABLE"
	BLOCKED        ItemVerdictStatus = "BLOCKED"
	NOTYETOPEN     ItemVerdictStatus = "NOT_YET_OPEN"
	OVERDUE        ItemVerdictStatus = "OVERDUE"
	QUOTAEXHAUSTED ItemVerdictStatus = "QUOTA_EXHAUSTED"
)

// Valid indicates whether the value is a known member of the ItemVerdictStatus enum.
func (e ItemVerdictStatus) Valid() bool {
	switch e {
	case AVAILABLE:
		return true
	case BLOCKED:
		return true
	case NOTYETOPEN:
		return true
	case OVERDUE:
		return true
	case QUOTAEXHAUSTED:
		return true
	default:
		return false
	}
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Service string             `json:"service"`
	Status  HealthStatusStatus `json:"status"`
	Time    *time.Time         `json:"time,omitempty"`
	Version string             `json:"version"`
}

// HealthStatusStatus defines model for HealthStatus.Status.
type HealthStatusStatus string

// ItemVerdict defines model for ItemVerdict.
type ItemVerdict struct {
	ItemCode        string            `json:"item_code"`
	NextAvailableAt *time.Time        `json:"next_available_at,omitempty"`
	Reasons         []Reason          `json:"reasons"`
	Status          ItemVerdictStatus `json:"status"`
}

// ItemVerdictStatus defines model for ItemVerdict.Status.
type ItemVerdictStatus string

// Problem Erro no formato RFC 7807 (problem+json).
type Problem struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	Type     *string `json:"type,omitempty"`
}

// Reason defines model for Reason.
type Reason struct {
	// Code Código máquina-legível que o front traduz em frase. Ex.: QUOTA_EXHAUSTED_WEEKLY, MISSING_PREREQ:aval-psiquiatrica.
	Code   string  `json:"code"`
	Detail *string `json:"detail,omitempty"`
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string
